theme = "hugo-theme-detox"
baseURL = "https://the-science-of-dating.netlify.app/"
languageCode = "en-us"
title = "The Science of Dating"
googleAnalytics = "UA-177543919-1"

[Params]
  description = "Data-proven Insights from 21st Century Dating"