theme = "hugo-theme-detox"
baseURL = "http://www.thescienceofdating.rbind.io/"
languageCode = "en-us"
title = "The Science of Dating"

[Params]
  description = "Data-proven Insights from 21st Century Dating"

