
[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
  HUGO_VERSION = "0.14.0"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --buildFuture "

[context.deploy-preview.environment]
  HUGO_VERSION = "0.14.0"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.14.0"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"